CREATE TABLE sementes_catalogo (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultura VARCHAR(50) NOT NULL,
    variedade VARCHAR(100) NOT NULL,
    ciclo VARCHAR(50) NOT NULL,
    resistencia_principal VARCHAR(150),
    tipo_solo_ideal VARCHAR(50),
    estoque_toneladas INT NOT NULL,
    preco_saca_brl DECIMAL(10, 2) NOT NULL
);

INSERT INTO sementes_catalogo 
    (cultura, variedade, ciclo, resistencia_principal, tipo_solo_ideal, estoque_toneladas, preco_saca_brl)
VALUES
    ('Soja', 'BRS Suprema 100', 'Precoce', 'Estresse hídrico (Seca)', 'Argiloso', 120, 185.50),
    ('Soja', 'AgroMax 20X', 'Tardio', 'Ferrugem Asiática e Nematoides', 'Misto', 300, 195.00),
    ('Soja', 'Pioneira 330', 'Médio', 'Alta umidade e percevejos', 'Arenoso', 45, 178.00),
    ('Soja', 'SafraForte 99', 'Precoce', 'Lagarta e mancha-alvo', 'Argiloso', 0, 190.00),
    ('Milho', 'Cargill 500 VIP', 'Precoce', 'Lagarta-do-cartucho', 'Misto', 500, 240.00),
    ('Milho', 'Trovão 8000', 'Médio', 'Estresse hídrico e cigarrinha', 'Arenoso', 210, 260.50),
    ('Milho', 'BRS Ouro Branco', 'Tardio', 'Ventos fortes e acamamento', 'Argiloso', 80, 225.00),
    ('Sorgo', 'AgroSorgo Gigante', 'Precoce', 'Seca extrema e pássaros', 'Arenoso', 150, 120.00),
    ('Sorgo', 'SorgoTech 40', 'Médio', 'Pulgão e doenças foliares', 'Misto', 30, 135.00);